language: python
python:
  - 2.6
  - 2.7
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get install -qq python-fontforge
install:
  - pip install . --use-mirrors
script: nosetests